import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Inline Worker Plugin
const inlineWorkerPlugin = {
  name: 'inline-worker',
  setup(build) {
    build.onResolve({ filter: /\.worker\.ts$/ }, args => {
        return {
            path: path.join(args.resolveDir, args.path),
            namespace: 'inline-worker'
        };
    });

    build.onLoad({ filter: /.*/, namespace: 'inline-worker' }, async args => {
        const result = await esbuild.build({
            entryPoints: [args.path],
            write: false,
            bundle: true,
            minify: prod, 
            format: 'iife',
            target: 'es2018',
        });

        const { text } = result.outputFiles[0];
        
        return {
            contents: `export default ${JSON.stringify(text)};`,
            loader: 'js',
        };
    });
  }
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [inlineWorkerPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
